name: Deploy to Production

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: landingpages

    steps:
      - uses: actions/checkout@v3
        
      - name: Move build to /var/www/jhonataslima
        run: |
          rm -rf /var/www/jhonataslima/*
          mv out/* /var/www/jhonataslima/
